inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Enabled: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: either_consistent
  UseHashRocketsWithSymbolValues: false
  PreferHashRocketsForNonAlnumEndingSymbols: false

Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
