inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Enabled: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
